kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080  # frontend
        hostPort: 30080
        protocol: TCP
      - containerPort: 30081  # backend
        hostPort: 30081
        protocol: TCP
      - containerPort: 30082  # streamer
        hostPort: 30082
        protocol: TCP
      - containerPort: 30083  # frontend-admin
        hostPort: 30083
        protocol: TCP