apiVersion: v1
kind: Secret
metadata:
  name: ginflix-secrets
  namespace: ginflix
type: Opaque
stringData:
  GARAGE_ENDPOINT: "###"
  GARAGE_USE_SSL: "false"
  GARAGE_BUCKET: "###"
  GARAGE_ACCESS_KEY: "###"
  GARAGE_SECRET_KEY: "###"